---
description: Chyba kompilátoru CS0156
title: Chyba kompilátoru CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: 3abffbc5ee21ce588a8d5b6c7e980fcc7f7bc2f0
ms.sourcegitcommit: d579fb5e4b46745fd0f1f8874c94c6469ce58604
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 08/30/2020
ms.locfileid: "89132219"
---
# <a name="compiler-error-cs0156"></a><span data-ttu-id="98e79-103">Chyba kompilátoru CS0156</span><span class="sxs-lookup"><span data-stu-id="98e79-103">Compiler Error CS0156</span></span>
<span data-ttu-id="98e79-104">Příkaz throw bez argumentů není povolený v klauzuli finally, která je vnořená do nejbližší nadřazené klauzule catch.</span><span class="sxs-lookup"><span data-stu-id="98e79-104">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>  
  
 <span data-ttu-id="98e79-105">Příkaz [throw](../language-reference/keywords/throw.md) bez parametrů může být použit pouze v klauzuli **catch** , která nepřijímá žádné parametry.</span><span class="sxs-lookup"><span data-stu-id="98e79-105">A [throw](../language-reference/keywords/throw.md) statement with no parameters can only appear in a **catch** clause that takes no parameters.</span></span>  
  
 <span data-ttu-id="98e79-106">Další informace naleznete v tématu [výjimky a zpracování výjimek](../programming-guide/exceptions/index.md).</span><span class="sxs-lookup"><span data-stu-id="98e79-106">For more information, see [Exceptions and Exception Handling](../programming-guide/exceptions/index.md).</span></span>  
  
 <span data-ttu-id="98e79-107">Následující ukázka generuje CS0156:</span><span class="sxs-lookup"><span data-stu-id="98e79-107">The following sample generates CS0156:</span></span>  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
