---
title: Příkaz throw nemůže vynechat operand vně příkazu catch nebo uvnitř příkazu finally.
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: c4ab115b01e78c245cbd9f564b50573d6e30c5e7
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 06/04/2020
ms.locfileid: "84414930"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a><span data-ttu-id="60d2f-102">Příkaz throw nemůže vynechat operand vně příkazu catch nebo uvnitř příkazu finally.</span><span class="sxs-lookup"><span data-stu-id="60d2f-102">'Throw' statement cannot omit operand outside a 'Catch' statement or inside a 'Finally' statement</span></span>
<span data-ttu-id="60d2f-103">`Throw`příkazy mimo `Catch` příkaz musí poskytovat název objektu výjimky.</span><span class="sxs-lookup"><span data-stu-id="60d2f-103">`Throw` statements outside of `Catch` statement must supply the name of an exception object.</span></span>  
  
 <span data-ttu-id="60d2f-104">**ID chyby:** BC30666</span><span class="sxs-lookup"><span data-stu-id="60d2f-104">**Error ID:** BC30666</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="60d2f-105">Oprava této chyby</span><span class="sxs-lookup"><span data-stu-id="60d2f-105">To correct this error</span></span>  
  
1. <span data-ttu-id="60d2f-106">Zadejte název objektu výjimky odvozený z `System.Exception` .</span><span class="sxs-lookup"><span data-stu-id="60d2f-106">Specify the name of an exception object derived from `System.Exception`.</span></span>  
  
2. <span data-ttu-id="60d2f-107">Restrukturalizujte kód tak, aby byl `Throw` příkaz uvnitř `Catch` bloku.</span><span class="sxs-lookup"><span data-stu-id="60d2f-107">Restructure your code so that the `Throw` statement is inside a `Catch` block.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="60d2f-108">Viz také</span><span class="sxs-lookup"><span data-stu-id="60d2f-108">See also</span></span>

- [<span data-ttu-id="60d2f-109">Throw – příkaz</span><span class="sxs-lookup"><span data-stu-id="60d2f-109">Throw Statement</span></span>](../language-reference/statements/throw-statement.md)
- [<span data-ttu-id="60d2f-110">Try...Catch....Finally – příkaz</span><span class="sxs-lookup"><span data-stu-id="60d2f-110">Try...Catch...Finally Statement</span></span>](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [<span data-ttu-id="60d2f-111">Zpracování a vyvolávání výjimek v rozhraní .NET</span><span class="sxs-lookup"><span data-stu-id="60d2f-111">Handling and throwing exceptions in .NET</span></span>](../../standard/exceptions/index.md)
