---
title: Výjimky a zpracování výjimek – Průvodce programováním v C#
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 0ba123fa9f9aacd0876f07bdf3ae7bb9159a6834
ms.sourcegitcommit: a241301495a84cc8c64fe972330d16edd619868b
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 06/01/2020
ms.locfileid: "84241705"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="3f28b-102">Výjimky a jejich zpracování (Průvodce programováním v C#)</span><span class="sxs-lookup"><span data-stu-id="3f28b-102">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="3f28b-103">Funkce zpracování výjimek v jazyce C# vám pomůžou při práci s případnými neočekávanými nebo mimořádnými situacemi, ke kterým dochází při spuštění programu.</span><span class="sxs-lookup"><span data-stu-id="3f28b-103">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="3f28b-104">Zpracování výjimek používá `try` `catch` `finally` klíčová slova, a k vyzkoušení akcí, které nemusí být úspěšné, pro zpracování selhání, pokud se rozhodnete, že je to vhodné, a za účelem vyčištění prostředků.</span><span class="sxs-lookup"><span data-stu-id="3f28b-104">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="3f28b-105">Výjimky mohou být generovány modulem CLR (Common Language Runtime), rozhraním .NET nebo knihovnami třetích stran nebo pomocí kódu aplikace.</span><span class="sxs-lookup"><span data-stu-id="3f28b-105">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="3f28b-106">Výjimky jsou vytvářeny pomocí `throw` klíčového slova.</span><span class="sxs-lookup"><span data-stu-id="3f28b-106">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="3f28b-107">V mnoha případech může být výjimka vyvolána metodou, kterou váš kód volá přímo, ale jinou metodou v zásobníku volání.</span><span class="sxs-lookup"><span data-stu-id="3f28b-107">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="3f28b-108">Pokud k tomu dojde, modul CLR zruší zásobník zpět, hledá metodu s `catch` blokem pro konkrétní typ výjimky a spustí první takový `catch` blok, který nalezne.</span><span class="sxs-lookup"><span data-stu-id="3f28b-108">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="3f28b-109">Pokud nenajde žádný odpovídající `catch` blok kdekoli v zásobníku volání, ukončí proces a zobrazí uživateli zprávu.</span><span class="sxs-lookup"><span data-stu-id="3f28b-109">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="3f28b-110">V tomto příkladu metoda Testuje dělení nulou a zachytí chybu.</span><span class="sxs-lookup"><span data-stu-id="3f28b-110">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="3f28b-111">Bez zpracování výjimek by tento program byl ukončen s **DivideByZeroException** chybou.</span><span class="sxs-lookup"><span data-stu-id="3f28b-111">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="3f28b-112">Přehled výjimek</span><span class="sxs-lookup"><span data-stu-id="3f28b-112">Exceptions Overview</span></span>

<span data-ttu-id="3f28b-113">Výjimky mají následující vlastnosti:</span><span class="sxs-lookup"><span data-stu-id="3f28b-113">Exceptions have the following properties:</span></span>

- <span data-ttu-id="3f28b-114">Výjimky jsou typy, ze kterých jsou nakonec odvozeny `System.Exception` .</span><span class="sxs-lookup"><span data-stu-id="3f28b-114">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="3f28b-115">Použijte `try` blok kolem příkazů, které mohou vyvolat výjimky.</span><span class="sxs-lookup"><span data-stu-id="3f28b-115">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="3f28b-116">Jakmile v bloku dojde k výjimce `try` , tok řízení přejde na první přidruženou obslužnou rutinu výjimky, která je přítomna kdekoli v zásobníku volání.</span><span class="sxs-lookup"><span data-stu-id="3f28b-116">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="3f28b-117">V jazyce C# se `catch` klíčové slovo používá k definování obslužné rutiny výjimky.</span><span class="sxs-lookup"><span data-stu-id="3f28b-117">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="3f28b-118">Pokud není k dispozici žádná obslužná rutina výjimky pro danou výjimku, program zastaví provádění s chybovou zprávou.</span><span class="sxs-lookup"><span data-stu-id="3f28b-118">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="3f28b-119">Nezachytit výjimku, pokud ji nemůžete zpracovat a opustit aplikaci ve známém stavu.</span><span class="sxs-lookup"><span data-stu-id="3f28b-119">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="3f28b-120">Pokud zachytíte `System.Exception` , znovu ji vyvolejte pomocí `throw` klíčového slova na konci `catch` bloku.</span><span class="sxs-lookup"><span data-stu-id="3f28b-120">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="3f28b-121">Pokud `catch` blok definuje proměnnou výjimky, můžete ji použít k získání dalších informací o typu výjimky, ke které došlo.</span><span class="sxs-lookup"><span data-stu-id="3f28b-121">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="3f28b-122">Výjimky mohou být explicitně generovány programem pomocí `throw` klíčového slova.</span><span class="sxs-lookup"><span data-stu-id="3f28b-122">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="3f28b-123">Objekty výjimek obsahují podrobné informace o chybě, jako je například stav zásobníku volání a textový popis chyby.</span><span class="sxs-lookup"><span data-stu-id="3f28b-123">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="3f28b-124">Kód v `finally` bloku je proveden i v případě, že je vyvolána výjimka.</span><span class="sxs-lookup"><span data-stu-id="3f28b-124">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="3f28b-125">Použijte `finally` blok k uvolnění prostředků, například pro zavření všech datových proudů nebo souborů, které byly otevřeny v `try` bloku.</span><span class="sxs-lookup"><span data-stu-id="3f28b-125">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="3f28b-126">Spravované výjimky v rozhraní .NET jsou implementovány nad mechanismem zpracování strukturované výjimky Win32.</span><span class="sxs-lookup"><span data-stu-id="3f28b-126">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="3f28b-127">Další informace naleznete v tématu [strukturované zpracování výjimek (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) a [průběh selhání na hloubkách zpracování strukturované výjimky Win32](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span><span class="sxs-lookup"><span data-stu-id="3f28b-127">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="3f28b-128">Související oddíly</span><span class="sxs-lookup"><span data-stu-id="3f28b-128">Related Sections</span></span>

<span data-ttu-id="3f28b-129">Další informace o zpracování výjimek a výjimek naleznete v následujících článcích:</span><span class="sxs-lookup"><span data-stu-id="3f28b-129">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="3f28b-130">Použití výjimek</span><span class="sxs-lookup"><span data-stu-id="3f28b-130">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="3f28b-131">Zpracování výjimek</span><span class="sxs-lookup"><span data-stu-id="3f28b-131">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="3f28b-132">Vytváření a vyvolávání výjimek</span><span class="sxs-lookup"><span data-stu-id="3f28b-132">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="3f28b-133">Výjimky generované kompilátorem</span><span class="sxs-lookup"><span data-stu-id="3f28b-133">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="3f28b-134">Postup zpracování výjimky pomocí try/catch (Průvodce programováním v C#)</span><span class="sxs-lookup"><span data-stu-id="3f28b-134">How to handle an exception using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="3f28b-135">Jak provést vyčištění kódu pomocí příkazu finally</span><span class="sxs-lookup"><span data-stu-id="3f28b-135">How to execute cleanup code using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="3f28b-136">Jak zachytit výjimku nekompatibilní se specifikací CLS</span><span class="sxs-lookup"><span data-stu-id="3f28b-136">How to catch a non-CLS exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="3f28b-137">Specifikace jazyka C#</span><span class="sxs-lookup"><span data-stu-id="3f28b-137">C# Language Specification</span></span>

<span data-ttu-id="3f28b-138">Další informace naleznete v tématu [výjimky](~/_csharplang/spec/exceptions.md) ve [specifikaci jazyka C#](/dotnet/csharp/language-reference/language-specification/introduction).</span><span class="sxs-lookup"><span data-stu-id="3f28b-138">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="3f28b-139">Specifikace jazyka je úplným a rozhodujícím zdrojem pro syntaxi a použití jazyka C#.</span><span class="sxs-lookup"><span data-stu-id="3f28b-139">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="3f28b-140">Viz také</span><span class="sxs-lookup"><span data-stu-id="3f28b-140">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="3f28b-141">Průvodce programováním v C#</span><span class="sxs-lookup"><span data-stu-id="3f28b-141">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="3f28b-142">Klíčová slova jazyka C#</span><span class="sxs-lookup"><span data-stu-id="3f28b-142">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="3f28b-143">throw</span><span class="sxs-lookup"><span data-stu-id="3f28b-143">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="3f28b-144">try-catch</span><span class="sxs-lookup"><span data-stu-id="3f28b-144">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="3f28b-145">try-finally</span><span class="sxs-lookup"><span data-stu-id="3f28b-145">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="3f28b-146">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="3f28b-146">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="3f28b-147">Výjimky</span><span class="sxs-lookup"><span data-stu-id="3f28b-147">Exceptions</span></span>](../../../standard/exceptions/index.md)
